spring:
  application:
    name: plaminskiy-research
  datasource:
    url: jdbc:postgresql://localhost:5432/pmva-plaminskiy
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
