spring:
  application:
    name: patan-spb
  datasource:
    url: jdbc:postgresql://localhost:5432/patan-spb
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
